Rework the output website elements and drop python 2
LIVVkit/LIVVkit pull request #53
Opened 2019-11-28 01:49 UTC by jhkennedy

currently, to produce the website as viewed in the browser, LIVVkit relies on a collection of Javascript functions that parse associated JSON files to dynamically create HTML. This is overly complicated as LIVVkit websites are static and makes customizing LIVVkit display elements hard (you have to edit the Javascript well away from where you create elements). 

This PR reworks the elements to be produced from customizable HTML templates through jinja2, and significantly simplifies both working with the elements and the required Javascript for the website. 

Additionally, as part of this effort, working with the classes and templates is significantly easier without trying to support python 2. Because Python 2 EOL is already here, this also drops python 2 support, moving the supported and tested python versions to 3.6 and up. 

Because of the significance of these changes, develop should now be considered to target the LIVVkit 3.0.0 release (version number bumped accordingly) and this major API change will break associated packages like LEX and EVV without updates. 

Fixes #30

2019-12-04 15:20 UTC, mkstratos requested changes
Aside from the one (possible) change in `livvkit/bundles/CISM_glissade/verification.py`, all looks good to me. Though, does `tests\conftest.py` ever get called when testing?

2019-12-04 15:20 UTC, mkstratos commented on livvkit/bundles/CISM_glissade/verification.py
> +        return elements.Error("Output Log", "Could not open file: " + file_path.split(os.sep)[-1]).__dict__
This returns a dict rather than the `elements.Error` Element, is that correct?

2019-12-06 20:22 UTC, jhkennedy commented on livvkit/bundles/CISM_glissade/verification.py
> +        return elements.Error("Output Log", "Could not open file: " + file_path.split(os.sep)[-1]).__dict__
Ooh, good catch.

2019-12-10 13:22 UTC, mkstratos approved these changes

2019-12-11 20:49 UTC, jhkennedy commented
@mkstratos I updated docs to reflect all these changes (and the changes in dev too). Once you're happy I'll do the merge. 

as for `conftest.py`, that's used by `pytest` when it's run -- it sets up some shared methods that will be available to all the tests. See:
* https://docs.pytest.org/en/2.7.3/plugins.html?highlight=re
* https://stackoverflow.com/questions/34466027/in-pytest-what-is-the-use-of-conftest-py-files

2019-12-11 21:28 UTC, mkstratos approved these changes
Joe, all looks good to me. Can you tag any other issues this will close?

2019-12-11 23:45 UTC, merged

2019-12-11 23:52 UTC, jhkennedy commented
Alright, all issues tagged and closed that this one fixes, plus I added some comments on other issues. 

Couple questions: 

1. Is this what we want to release for LIVVkit 3.0? 
2. If so, do you want:
    1. Me to do all the release steps? (merge to master, pypi, conda-forge)
    2. You to do all the release step?
   
   Either way, I'll write add documentation for how to do it all